name: 'Log Metric'
description: 'Log data point to a metric with the provided value. If the metric is not there, it will create one.'
inputs:
  metric-name:
    description: 'target metric name'
    required: true
  value:
    description: 'the value to log to the metric'
    required: true
  SITE_URL:
    description: 'target AWS account credentials'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      with:
        aws-access-key-id: ${{ inputs.SITE_URL }}
        aws-secret-access-key: ${{ inputs.SITE_URL }}
        aws-region: us-east-1
      shell: bash
      run: echo "Nice!"
