name: 'Log Metric'
description: 'Log data point to a metric with the provided value. If the metric is not there, it will create one.'
inputs:
  metric-name:
    description: 'target metric name'
    required: true
  value:
    description: 'the value to log to the metric'
    required: true
  SITE_URL:
    description: 'target AWS account credentials'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: echo "${{ inputs.working-directory }}"
