# Description: this workflow runs build mega-apps that have all the connected components.

name: Build System Test Canary

permissions:
  id-token: write # This is required for aws-actions/configure-aws-credentials

on:
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes

jobs:
  build-system-test:
    uses: ./.github/workflows/reusable-build-system-test.yml
    secrets:
      METRIC_LOGGER_ROLE_ARN: ${{ secrets.METRIC_LOGGER_ROLE_ARN }}
