# Description: this workflow runs build mega-apps that have all the connected components.

name: Mega App Canary - React

on:
  push:
    branches:
      - 'mega-app-canary'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        framework: [react]
        framework-version: [latest]
        build-tool: [cra]
        build-tool-version: [latest]
        pkg-manager: [npm]
        language: [ts]
        node-version: [18]
        include:
          - framework: react
            framework-version: latest
            build-tool: cra
            build-tool-version: latest
            pkg-manager: npm
            language: ts
            node-version: 16
          - framework: react
            framework-version: 16
            build-tool: cra
            build-tool-version: latest
            pkg-manager: npm
            language: ts
            node-version: 18
          - framework: react
            framework-version: latest
            build-tool: cra
            build-tool-version: latest
            pkg-manager: npm
            language: js
            node-version: 18
          - framework: react
            framework-version: latest
            build-tool: cra
            build-tool-version: latest
            pkg-manager: yarn
            pkg-manager-version: 1.22.19
            language: ts
            node-version: 18
          - framework: react
            framework-version: 17
            build-tool: next
            build-tool-version: 11
            pkg-manager: npm
            language: ts
            node-version: 16
          - framework: react
            framework-version: latest
            build-tool: next
            build-tool-version: latest
            pkg-manager: npm
            language: ts
            node-version: 18
          # TODO: add hard-coded gatsby
          # - framework: react
          #   framework-version: latest
          #   build-tool: gatsby
          #   build-tool-version: latest
          #   pkg-manager: npm
          #   language: ts
          #   node-version: 18
          - framework: react
            framework-version: latest
            build-tool: vite
            build-tool-version: latest
            pkg-manager: npm
            language: ts
            node-version: 18
          - framework: react
            framework-version: latest
            build-tool: vite
            build-tool-version: 2
            pkg-manager: npm
            language: ts
            node-version: 18

    env:
      MEGA_APP_NAME: ${{ matrix.framework }}-${{ matrix.framework-version }}-${{ matrix.build-tool }}-${{ matrix.build-tool-version }}-node-${{ matrix.node-version }}-${{ matrix.language }}
      DEPENDENCIES: react@${{ matrix.framework-version }} react-dom@${{ matrix.framework-version }} @aws-amplify/ui-react aws-amplify @aws-amplify/ui-react-storage
      DEP_TYPES: '@types/react@${{ matrix.framework-version }} @types/react-dom@${{ matrix.framework-version }}'

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          persist-credentials: false
      - name: Setup Node.js ${{ matrix.node-version }} with ${{ matrix.pkg-manager }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.pkg-manager }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Install build-system-tests package
        uses: ./.github/actions/install-with-retries
        with:
          working-directory: ./build-system-tests
      - name: Create MegaApp ${{ matrix.framework }}-${{ matrix.framework-version }}-${{ matrix.build-tool }}-${{ matrix.build-tool-version }}-node-${{ matrix.node-version }}-${{ matrix.language }}
        run: ./.github/scripts/create-mega-app.sh
        shell: bash
        env:
          BUILD_TOOL: ${{ matrix.build-tool }}
          LANGUAGE: ${{ matrix.language }}
          MEGA_APP_NAME: ${{ matrix.framework }}-${{ matrix.framework-version }}-${{ matrix.build-tool }}-${{ matrix.build-tool-version }}-node-${{ matrix.node-version }}-${{ matrix.language }}
          BUILD_TOOL_VERSION: ${{ matrix.build-tool-version }}
      - name: Copy aws_export and App.js
        run: ./.github/scripts/copy-mega-app-files.sh
        shell: bash
        env:
          BUILD_TOOL: ${{ matrix.build-tool }}
          LANGUAGE: ${{ matrix.language }}
          MEGA_APP_NAME: ${{ matrix.framework }}-${{ matrix.framework-version }}-${{ matrix.build-tool }}-${{ matrix.build-tool-version }}-node-${{ matrix.node-version }}-${{ matrix.language }}
          BUILD_TOOL_VERSION: ${{ matrix.build-tool-version }}
          FRAMEWORK_VERSION: ${{ matrix.framework-version }}
      - name: Install @aws-amplify/ui-react aws-amplify and build
        run: |
          if ${{ matrix.pkg-manager == 'yarn' }};then
            echo "yarn version"
            yarn -v
            echo "yarn set version ${{ matrix.pkg-manager-version }}"
            yarn set version ${{ matrix.pkg-manager-version }}
            echo "yarn version"
            yarn -v
            if ${{ matrix.build-tool == 'cra' && matrix.language == 'ts' }};then
              yarn add $DEP_TYPES
            fi
            yarn add $DEPENDENCIES
            yarn build
          else
            if ${{ matrix.build-tool == 'cra' && matrix.language == 'ts' }};then
              npm install $DEP_TYPES
            fi
            if ${{ matrix.build-tool == 'next' && matrix.build-tool-version == '11' }};then
              rm -rf node_modules
            fi
            npm install $DEPENDENCIES
            npm run build
          fi
        working-directory: build-system-tests/mega-apps/${{ matrix.framework }}-${{ matrix.framework-version }}-${{ matrix.build-tool }}-${{ matrix.build-tool-version }}-node-${{ matrix.node-version }}-${{ matrix.language }}
