name: Run Builds

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5,17 * * *'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Paths for each example app we want to test build on
        path:
          - angular/angularcli
          - react/cra
          - react/cra-ts
          - react/next
          - vue/vite
          - vue/vuecli
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: cd into the example app directory
        run: cd canary && cd ${{ matrix.path }}
      - name: Install packages
        run: yarn --no-lockfile
      - name: Build example app
        run: yarn build
