name: Run Builds

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 */2 * * *'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Paths for each example app we want to test build on
        path:
          - angular/angularcli
          - react/cra
          - react/cra-ts
          - react/next
          - vue/vite
          - vue/vuecli
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Ignore monorepo postcss.config.js
        run: mv postcss.config.js _postcss.config.js
      - name: Install packages
        run: yarn install --no-lockfile
        working-directory: ./canary/${{ matrix.path }}
      - name: Build example app
        run: yarn build
        working-directory: ./canary/${{ matrix.path }}

  trigger-alarm:
    # Triggers an alarm if any of builds failed.
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - run: echo "Not yet implemented"
